// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Customer struct {
	ID   int64          `db:"id" json:"id"`
	Name sql.NullString `db:"name" json:"name"`
}

type Order struct {
	ID         int64  `db:"id" json:"id"`
	CustomerID int64  `db:"customer_id" json:"customer_id"`
	JsonData   string `db:"json_data" json:"json_data"`
}

type Toy struct {
	ID         int64          `db:"id" json:"id"`
	Identifier string         `db:"identifier" json:"identifier"`
	Available  int64          `db:"available" json:"available"`
	JsonData   sql.NullString `db:"json_data" json:"json_data"`
}
